<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BionicSquare.DataAccess\BionicSquare.DataAccess.csproj" />
        <ProjectReference Include="..\BionicSquare.Models\BionicSquare.Models.csproj" />
        <ProjectReference Include="..\BionicSquare.Utility\BionicSquare.Utility.csproj" />
    </ItemGroup>

</Project>
